
export const API_ENDPOINT_DUMMY_BASE_URL = 'https://jsonplaceholder.typicode.com/';
export const FETCH_ALL_POST_ACTION = 'FETCH_POST_ACTION';
export const FETCH_ALL_POST_ACTION_SUCCESS = 'FETCH_ALL_POST_ACTION_SUCCESS';
export const FETCH_ALL_POST_ACTION_ERROR = 'FETCH_ALL_POST_ACTION_ERROR';
export const SAVE_ADD_DATA = 'SAVE_ADD_DATA';
export const FETCH_CURRENT_POST_ACTION = 'FETCH_CURRENT_POST_ACTION';
export const FETCH_CURRENT_POST_ACTION_SUCCESS = 'FETCH_CURRENT_POST_ACTION_SUCCESS';
export const FETCH_CURRENT_POST_ACTION_ERROR = 'FETCH_CURRENT_POST_ACTION_ERROR';
